### ISSUE TITLE
RxBinding 使用問題

### ISSUE THREAD

**Issue by Samsu7609** [SpikeKing/TestDetailRxAndroid#1]
請問一下
RxView.clicks(mFabFab).subscribe(this::onFabClicked);

 Observable<Boolean> checkEmail = RxTextView.textChangeEvents(emailEdit)
                .map(new Func1<TextViewTextChangeEvent, Boolean>() {
                    @Override
                    public Boolean call(TextViewTextChangeEvent textViewTextChangeEvent) {
                        boolean isEmpty = TextUtils.isEmpty(textViewTextChangeEvent.text().toString());
                        return !isEmpty;
                    }
                });

這樣子使用 在離開Activity 時候 需要做反註冊嗎 ？ 這樣會造成memory leak嗎？
感謝您

**Comment by panhs** [comment]
这种都是缺省都是在主线程操作，没有切换线程不用担心内存泄漏
